version: '3.7'

services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./Backend/db_setup:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql

    web:
        image: nginx:latest
        ports:
            - '8081:80'
        expose:
            - '80'
        volumes:
            - ./Backend/php:/code
            - ./Backend/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: ./Backend/
            dockerfile: Dockerfile
        # image: php:fpm-alpine
        expose:
            - '9000'
        volumes:
            - ./Backend/php:/code
        depends_on:
            - db
