version: '3.7'

services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - ./db_setup:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql0

    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        expose:
            - '8080'
        volumes:
            - ./php:/php
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: ./
            dockerfile: Dockerfile
        # image: php:fpm-alpine
        expose:
            - '9000'
        volumes:
            - ./php:/php
        depends_on:
            - db
