version: '3.7'

services:
    web:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - ./php:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./php:/code
        networks:
            - code-network

    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - 3306:3306
        volumes:
            - ./db:/db

networks:
    code-network:
        driver: bridge
