version: '3.7'

services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
        volumes:
            - ./db_setup:/docker-entrypoint-initdb.d/
            - ./db:/var/lib/mysql

    web:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - ./php:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    php:
        build:
            context: ./
            dockerfile: Dockerfile
        # image: php:fpm-alpine
        volumes:
            - ./php:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
